imports:
    - { resource: parameters.yml }

framework:
    secret: %kernel.secret%
    assets: ~
    templating:
        engines: ['twig']

doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8